### ISSUE TITLE
For new Versiom

### ISSUE THREAD

**Issue by dkkaran1996** [masterfermin02/vici-admin-them#20]
Is it available for updated vicidial versions?

Vicidial new version updated in real-time monitoring report and some changes in admin.php?

So updated theme available?

**Comment by masterfermin02** [comment]
yes, this theme is available for updated version of vicidial. The real-time version should not has all the feature up to date because is a custom version of it that I did 4 years ago.

If you see any problem you can create an issue or open a pull request and I will be more than happy to take a look.

**Comment by dkkaran1996** [comment]
For theme also,

There is an issue in Inbound. There is misalignment.
*Regards,*
*Er.D.Kirubhakaran B.E.*
